/* Snapshot statico della sola fonte Fantacalcio.it: nessun fetch durante l'asta. */
const lineupNames = (value) => value ? value.split('|') : [];
const LINEUP_DATA = {
  sourceUpdatedAt: '2026-09-03',
  sources: ['Fantacalcio.it'],
  sourceUrl: 'https://www.fantacalcio.it/news/calcio-italia/06_08_2026/asta-fantacalcio-le-probabili-formazioni-della-serie-a-enilive-2026-27-495558',
  teams: [
    { team:'Atalanta', starters:lineupNames('Carnesecchi|Bellanova|Kristensen|Scalvini|Bernasconi|Kessie|Gaetano|Ederson|De Ketelaere|Scamacca|Rowe'), doubts:lineupNames('Bellanova|Zappacosta|Kristensen|Hien|Kessie|Samardzic|Scamacca|Krstovic|Rowe|Raspadori'), penalties:lineupNames('Scamacca|Krstovic|Samardzic'), setPieces:lineupNames('De Ketelaere|Samardzic|Gaetano') },
    { team:'Bologna', starters:lineupNames('Skorupski|Zortea|Heggem|Theate|Miranda|Odgaard|Ferguson|Pobega|Orsolini|Dovbyk|Cambiaghi'), doubts:lineupNames('Pobega|Moro|Odgaard|Amondarain|Orsolini|Bernardeschi|Piccoli|Dovbyk|Cambiaghi|Mbangula'), penalties:lineupNames('Orsolini|Bernardeschi|Dovbyk'), setPieces:lineupNames('Orsolini|Bernardeschi|Miranda') },
    { team:'Cagliari', starters:lineupNames('Caprile|Ze Pedro|Mina|Rodriguez|Obert|Adopo|Winks|Romano|Fazzini|Maldini|Kevin Carlos'), doubts:lineupNames('Zè Pedro|Sugawara|Adopo|Fadera|Kevin Carlos|Nzola'), penalties:lineupNames('Nzola|Kevin Carlos|Mina'), setPieces:lineupNames('Fazzini|Maldini|Romano') },
    { team:'Como', starters:lineupNames('Butez|Couto|Chalobah|Ramon|Valle|Da Cunha|Perrone|Diao|Paz|Baturina|Kean'), doubts:lineupNames('Couto|Smolcic|Valle|Kaiki|Diao|Rodriguez|Baturina|Milla|Kean|Douvikas'), penalties:lineupNames('Da Cunha|Kean|Douvikas'), setPieces:lineupNames('Paz|Baturina|Milla') },
    { team:'Fiorentina', starters:lineupNames('De Gea|Jimenez|Dragusin|Viery|Valdepenas|Ndour|Fagioli|Atta|Mastantuono|Beto|Goncalves'), doubts:lineupNames('Jimenez|Joao Mario|Viery|Pongracic|Fagioli|Oulai|Goncalves|Njie|Beto|Pellegrino'), penalties:lineupNames('Beto|Pellegrino|Goncalves'), setPieces:lineupNames('Mastantuono|Atta|Goncalves') },
    { team:'Frosinone', starters:lineupNames('Palmisani|Tchato|Calvani|Monterisi|Bracaglia|Grillitsch|Calò|Ghedjemis|Schimd|Kvernadze|Raimondo'), doubts:lineupNames('Tchato|Oyono|Bracaglia|Terzic|Grillitsch|Cichella|Raimondo|Bobcek|Ghedjemis|Zerbin'), penalties:lineupNames('Calò|Schimd|Bobcek'), setPieces:lineupNames('Calò|Schimd|Ghedjemis') },
    { team:'Genoa', starters:lineupNames('Bijlow|Marcandalli|Ostigard|Vasquez|Ellertsson|Frendrup|Sow|Mitaj|Baldanzi|Vitinha|Colombo'), doubts:lineupNames('Mitaj|Puczka|Sow|Amorim|Vitinha|El Shaarawy|Colombo|Osmajic'), penalties:lineupNames('Colombo|Ostigard|Vitinha'), setPieces:lineupNames('Baldanzi|Vitinha|Messias') },
    { team:'Inter', starters:lineupNames('Martinez|Bisseck|Akanji|Bastoni|Spence|Barella|Calhanoglu|Jones|Dimarco|Thuram|Lautaro'), doubts:lineupNames('Bisseck|Stones|Spence|Diouf|Jones|Zielinski|Thuram|Pio Esposito'), penalties:lineupNames('Calhanoglu|Zielinski|Lautaro Martinez'), setPieces:lineupNames('Calhanoglu|Dimarco|Zielinski') },
    { team:'Juventus', starters:lineupNames('Vicario|Kalulu|Bremer|Lucumì|Celik|Locatelli|Sarr|Conceicao|McKennie|Gonzalez|Kolo Muani'), doubts:lineupNames('Lucumì|Kelly|Celik|Cambiaso|Sarr|Douglas Luiz|Nico Gonzalez|Alajbegovic|Kolo Muani|Woltemade'), penalties:lineupNames('Kolo Muani|Woltemade|Gonzalez'), setPieces:lineupNames('Yildiz|Locatelli|Douglas Luiz') },
    { team:'Lazio', starters:lineupNames('Mandas|Marusic|Sutalo|Provstgaard|Tavares|Frattesi|Rovella|Taylor|Isaksen|Pinamonti|Zaccagni'), doubts:lineupNames('Marusic|Floriani|Sutalo|Doekhi|Tavares|Pedraza|Isaksen|Cancellieri|Pinamonti|Gudmundsson'), penalties:lineupNames('Zaccagni|Pinamonti|Gudmundsson'), setPieces:lineupNames('Rovella|Zaccagni|Gudmundsson') },
    { team:'Lecce', starters:lineupNames('Falcone|Danilo Veiga|Gaspar|Tiago Gabriel|Gallo|Coulibaly|Ilic|Berisha|Pierotti|Geubbels|Monteiro'), doubts:lineupNames('Ilic|Ngom|Berisha|Gandelman|Geubbels|Stulic|Monteiro|Fatah'), penalties:lineupNames('Geubbels|Stulic|Berisha'), setPieces:lineupNames('Pierotti|Berisha|Gallo') },
    { team:'Milan', starters:lineupNames('Maignan|Gila|Gabbia|Pavlovic|Moreira|Modric|Musah|Bartesaghi|Rabiot|Pulisic|Ramos'), doubts:lineupNames('Gabbia|De Winter|Bartesaghi|Chukwueze|Musah|Loftus-Cheek|Pulisic|Saelemaekers|Cisse'), penalties:lineupNames('Ramos|Pulisic|Modric'), setPieces:lineupNames('Modric|Pulisic|Saelemaekers') },
    { team:'Monza', starters:lineupNames('Tornqvist|Ziolkowski|Lucchesi|Carboni|Birindelli|Tourè|Akinsanmiro|Mangas|Ngonge|Folorunsho|Varela'), doubts:lineupNames('Ziolkowski|Kouadio|Ngonge|Colpani|Varela|Cutrone|Tourè|Mout|Birindelli|Zeballos'), penalties:lineupNames('Cutrone|Varela|Ngonge'), setPieces:lineupNames('Ngonge|Folorunsho|Pessina') },
    { team:'Napoli', starters:lineupNames('Meret|Di Lorenzo|Rrahmani|Badiashile|Spinazzola|De Bruyne|Lobotka|McTominay|Politano|Hojlund|Alisson Santos'), doubts:lineupNames('Badiashile|Buongiorno|Spinazzola|Olivera|De Bruyne|Anguissa|Politano|Vergara|Neres'), penalties:lineupNames('De Bruyne|Hojlund|Politano'), setPieces:lineupNames('De Bruyne|Politano|Neres') },
    { team:'Parma', starters:lineupNames('Corvi|Delprato|Troilo|Diego Carlos|Valeri|Fabbian|Keita|Ordonez|Bernabè|Romero|Tourè'), doubts:lineupNames('Corvi|Daffara|Romero|Elphege|Fabbian|Britschgi'), penalties:lineupNames('Tourè|Romero|Valeri'), setPieces:lineupNames('Bernabè|Nicolussi Caviglia|Valeri') },
    { team:'Roma', starters:lineupNames('Svilar|Mancini|N’Dicka|Hermoso|Molina|Koné|Cristante|Wesley|Dybala|Mora|Malen'), doubts:lineupNames('Hermoso|Koulierakis|Mora|Soulè|Dybala|Castro'), penalties:lineupNames('Malen|Dybala|Castro'), setPieces:lineupNames('Dybala|Malen|Pellegrini') },
    { team:'Sassuolo', starters:lineupNames('Muric|Van der Brempt|Idzes|Caleta-Car|Obrador|Thorstvedt|Matic|Adzic|Berardi|Esposito|Laurientè'), doubts:lineupNames('Caleta-Car|Leysen|Obrador|Doig|Adzic|Bakola|Esposito|Bowie'), penalties:lineupNames('Berardi|Esposito|Laurientè'), setPieces:lineupNames('Berardi|Laurientè|Adzic') },
    { team:'Torino', starters:lineupNames('Perri|Comuzzo|Coco|Comert|Belghali|Mandragora|Fitz-Jim|Cacciamani|Casadei|Vlasic|Simeone'), doubts:lineupNames('Coco|Ismajli|Belghali|Patterson|Cacciamani|Fortini|Casadei|Braganca|Adams'), penalties:lineupNames('Vlasic|Simeone|Mandragora'), setPieces:lineupNames('Vlasic|Mandragora|Gineitis') },
    { team:'Udinese', starters:lineupNames('Okoye|Palma|Kabasele|Solet|Vojvoda|Piotrowski|Karlstrom|Kamara|Zaniolo|Ekkelenkamp|Davis'), doubts:lineupNames('Palma|Abankwah|Piotrowski|Miller'), penalties:lineupNames('Davis|Solet|Zaniolo'), setPieces:lineupNames('Zaniolo|Ekkelenkamp|Unai Gomez') },
    { team:'Venezia', starters:lineupNames('Stankovic|Schingtienne|Bella-Kotchap|Juan Jesus|Mazzocchi|Kike Perez|Busio|Basic|Haps|Yeboah|Akor Adams'), doubts:lineupNames('Juan Jesus|Halhal|Mazzocchi|Hainaut|Haps|Correia|Perez|Sohm|Adams|Rrahmani'), penalties:lineupNames('Busio|Adams|Adorante'), setPieces:lineupNames('Busio|Yeboah|Kike Perez') },
  ],
};
