/* Snapshot statico: solo XI, ballottaggi, rigoristi e piazzati. Nessun fetch runtime. */
const lineupNames = (value) => value ? value.split('|') : [];
const LINEUP_DATA = {
  sourceUpdatedAt: '2026-09-03',
  sources: ['Fantacalcio.it', 'SOS Fanta'],
  teams: [
    { team:'Atalanta', starters:lineupNames('Carnesecchi|Scalvini|Kessie|Gaetano|Ederson|De Ketelaere'), doubts:lineupNames('Bellanova|Zappacosta|Kristensen|Hien|Bernasconi|Kolasinac|Scamacca|Krstovic|Rowe|Raspadori|Samardzic'), penalties:lineupNames('Scamacca|Krstovic|Samardzic'), setPieces:lineupNames('De Ketelaere|Samardzic|Gaetano') },
    { team:'Bologna', starters:lineupNames('Skorupski|Theate|Ferguson'), doubts:lineupNames('Zortea|Holm|Heggem|Helland|Pobega|Moro|Odgaard|Amondarain|Orsolini|Bernardeschi|Dovbyk|Piccoli|Cambiaghi|Mbangula'), penalties:lineupNames('Orsolini|Bernardeschi|Dovbyk'), setPieces:lineupNames('Orsolini|Bernardeschi|Miranda') },
    { team:'Cagliari', starters:lineupNames('Caprile|Rodriguez|Obert|Winks|Romano|Fazzini|Maldini'), doubts:lineupNames('Ze Pedro|Zè Pedro|Sugawara|Mina|Deiola|Adopo|Fadera|Kevin Carlos|Mendy|Nzola'), penalties:lineupNames('Nzola|Kevin Carlos|Mina'), setPieces:lineupNames('Fazzini|Maldini|Romano') },
    { team:'Como', starters:lineupNames('Chalobah|Ramon|Paz|Baturina'), doubts:lineupNames('Butez|Sanchez|Couto|Smolcic|Valle|Kaiki|Da Cunha|Perrone|Milla|Diao|Rodriguez|Kean|Douvikas'), penalties:lineupNames('Da Cunha|Kean|Douvikas'), setPieces:lineupNames('Paz|Baturina|Milla') },
    { team:'Fiorentina', starters:lineupNames('De Gea|Dragusin|Atta|Ndour|Mastantuono'), doubts:lineupNames('Jimenez|Dodò|Dodo|Viery|Pongracic|Valdepenas|Joao Mario|Fagioli|Oulai|Goncalves|Gonçalves|Njie|Beto|Pellegrino'), penalties:lineupNames('Beto|Pellegrino|Goncalves'), setPieces:lineupNames('Mastantuono|Atta|Goncalves') },
    { team:'Frosinone', starters:lineupNames('Calvani|Monterisi|Calò|Calo|Grillitsch|Schmid|Kvernadze'), doubts:lineupNames('Palmisani|Desplanches|Tchato|Oyono|Bracaglia|Terzic|Ghedjemis|Fini|Zerbin|Raimondo|Bobcek'), penalties:lineupNames('Calò|Schmid|Bobcek'), setPieces:lineupNames('Calò|Schmid|Ghedjemis') },
    { team:'Genoa', starters:lineupNames('Bijlow|Marcandalli|Ostigard|Vasquez|Drameh|Frendrup|Baldanzi|Colombo'), doubts:lineupNames('Mitaj|Ellertsson|Sow|Amorim|Vitinha|Osmajic|Meichtry'), penalties:lineupNames('Colombo|Ostigard|Vitinha'), setPieces:lineupNames('Baldanzi|Vitinha|Messias') },
    { team:'Inter', starters:lineupNames('Akanji|Bastoni|Barella|Calhanoglu|Dimarco|Martinez L.|Lautaro Martinez'), doubts:lineupNames('Martinez Jo.|Josep Martinez|Provedel|Bisseck|Stones|Spence|Diouf|Jones C.|Jones|Zielinski|Thuram|Pio Esposito'), penalties:lineupNames('Calhanoglu|Zielinski|Martinez L.'), setPieces:lineupNames('Calhanoglu|Dimarco|Zielinski') },
    { team:'Juventus', starters:lineupNames('Vicario|Kalulu|Bremer|Locatelli|Conceicao|McKennie'), doubts:lineupNames('Lucumi|Lucumì|Kelly|Celik|Cambiaso|Sarr|Douglas Luiz|Thuram K.|Gonzalez|Nico Gonzalez|Alajbegovic|Kolo Muani|Woltemade|Yildiz'), penalties:lineupNames('Kolo Muani|Woltemade|Gonzalez'), setPieces:lineupNames('Yildiz|Locatelli|Douglas Luiz') },
    { team:'Lazio', starters:lineupNames('Mandas|Marusic|Provstgaard|Taylor|Frattesi|Zaccagni|Pinamonti'), doubts:lineupNames('Doekhi|Sutalo|Tavares|Pedraza|Isaksen|Cancellieri|Gudmundsson|Rovella|Cataldi'), penalties:lineupNames('Zaccagni|Pinamonti|Gudmundsson'), setPieces:lineupNames('Rovella|Zaccagni|Gudmundsson') },
    { team:'Lecce', starters:lineupNames('Falcone|Danilo Veiga|Veiga D.|Gaspar|Tiago Gabriel|Gallo|Coulibaly|Pierotti'), doubts:lineupNames('Ilic|Ngom|Berisha|Gandelman|Geubbels|Stulic|Monteiro|Fatah|Gorter'), penalties:lineupNames('Geubbels|Stulic|Berisha'), setPieces:lineupNames('Pierotti|Berisha|Gallo') },
    { team:'Milan', starters:lineupNames('Maignan|Gila|Pavlovic|Rabiot|Modric|Moreira|Ramos|Goncalo Ramos'), doubts:lineupNames('Gabbia|De Winter|Bartesaghi|Chukwueze|Musah|Loftus-Cheek|Pulisic|Saelemaekers|Cisse|Cissè'), penalties:lineupNames('Ramos|Pulisic|Modric'), setPieces:lineupNames('Modric|Pulisic|Saelemaekers') },
    { team:'Monza', starters:lineupNames('Tornqvist|Carboni|Mangas|Folorunsho'), doubts:lineupNames('Ziolkowski|Kouadio|Lucchesi|Goglichidze|Tourè|Toure|Birindelli|Akinsanmiro|Ngonge|Colpani|Ciurria|Varela|Cutrone|Mota|Zeballos|Pessina'), penalties:lineupNames('Cutrone|Varela|Ngonge'), setPieces:lineupNames('Ngonge|Folorunsho|Pessina') },
    { team:'Napoli', starters:lineupNames('Meret|Di Lorenzo|Rrahmani|Lobotka|McTominay|Mctominay|Hojlund|Alisson Santos|Santos A.'), doubts:lineupNames('Badiashile|Buongiorno|Marin|Spinazzola|Olivera|De Bruyne|Anguissa|Politano|Vergara|Neres'), penalties:lineupNames('De Bruyne|Hojlund|Politano'), setPieces:lineupNames('De Bruyne|Politano|Neres') },
    { team:'Parma', starters:lineupNames('Delprato|Troilo|Diego Carlos|Valeri|Keita|Bernabè|Bernabe|Tourè|Toure'), doubts:lineupNames('Corvi|Daffara|Fabbian|Ordonez|Romero|Elphege|Lontani'), penalties:lineupNames('Tourè|Romero|Valeri'), setPieces:lineupNames('Bernabè|Nicolussi Caviglia|Valeri') },
    { team:'Roma', starters:lineupNames('Svilar|Mancini|N’Dicka|N\'Dicka|Ndicka|Molina|Koné|Kone|Cristante|Wesley|Malen'), doubts:lineupNames('Hermoso|Koulierakis|Dybala|Castro|Mora|Soulè|Soule'), penalties:lineupNames('Malen|Dybala|Castro'), setPieces:lineupNames('Dybala|Malen|Pellegrini') },
    { team:'Sassuolo', starters:lineupNames('Muric|Van der Brempt|Idzes|Matic|Berardi|Laurientè|Lauriente'), doubts:lineupNames('Caleta-Car|Leysen|Walukiewicz|Obrador|Doig|Thorstvedt|Adzic|Esposito|Bowie|Bakola'), penalties:lineupNames('Berardi|Esposito|Laurientè'), setPieces:lineupNames('Berardi|Laurientè|Adzic') },
    { team:'Torino', starters:lineupNames('Perri|Comuzzo|Coco|Belghali|Mandragora|Fitz-Jim|Cacciamani|Vlasic|Simeone'), doubts:lineupNames('Comert|Ismajli|Patterson|Fortini|Casadei|Braganca|Adams'), penalties:lineupNames('Vlasic|Simeone|Mandragora'), setPieces:lineupNames('Vlasic|Mandragora|Gineitis') },
    { team:'Udinese', starters:lineupNames('Solet|Vojvoda|Karlstrom|Kamara|Zaniolo|Ekkelenkamp|Davis'), doubts:lineupNames('Palma|Abankwah|Kabasele|Bertola|Piotrowski|Miller'), penalties:lineupNames('Davis|Solet|Zaniolo'), setPieces:lineupNames('Zaniolo|Ekkelenkamp|Unai Gomez') },
    { team:'Venezia', starters:lineupNames('Stankovic|Stankovic F.|Schingtienne|Bella-Kotchap|Busio|Basic|Yeboah|Yeboah J.'), doubts:lineupNames('Juan Jesus|Halhal|Mazzocchi|Hainaut|Haps|Correia|Kike Perez|Perez K.|Sohm|Adams|Akor Adams|Rrahmani'), penalties:lineupNames('Busio|Adams|Adorante'), setPieces:lineupNames('Busio|Yeboah|Kike Perez') },
  ],
};
